const os = require('os');
const yaml = require('yaml');
const readSource = require('./readSource');
const transform = require('./transform');
const renderSass = require('./renderSass');
const renderJs = require('./renderJs');
const path = require('path');
const renderJson = require('./renderJson');

const sassComment = `// stylelint-disable
// DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Webpack.
// Design tokens should be edited in _patterns/00-config/config.design-tokens.yml`;

const jsComment = `/* eslint-disable */
// DO NOT EDIT THIS FILE.  This is a gitignored artifact created by Webpack.
// Design tokens should be edited in _patterns/00-config/config.design-tokens.yml`;

module.exports = async function (source) {
  const callback = this.async();
  const themeSettings = path.resolve(__dirname + '/../theme-settings.json');
  this.addDependency(themeSettings);
  const data = await readSource(source);
  const transformed = await transform(data);
  const sass = sassComment + os.EOL + renderSass(transformed.data);
  const js = jsComment + os.EOL + renderJs(transformed.data);
  const json = await renderJson(transformed.data, themeSettings);
  this.emitFile('../source/00-config/_design-tokens.artifact.scss', sass);
  this.emitFile('../source/00-config/_GESSO.es6.js', js);
  this.emitFile('../theme.json', json);
  callback(null, yaml.stringify(transformed.data));
  return source;
};
